### ISSUE TITLE
About customization

### ISSUE THREAD

**Issue by gopinadh39** [wermerb/ngx-mqtt-client#2]
I am not able to give my own broker in app module
NgxMqttClientModule.withOptions({
      host: '192.186.3.39',
      protocol: 'ws',
      port: 1883,
      path: '/mqtt'
    })
I,ve tried this but it shows 
WebSocket connection to 'ws://192.186.3.39:1883/mqtt' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

**Comment by wermerb** [comment]
Have you checked your mqtt is online and also to able to receive ws connection?

**Comment by gopinadh39** [comment]
@wermerb Thank you for the quick reply.

My mqtt server isnt accepting 'ws' I think. So i tried to connect to it using 'mqtt' in MQTTBox chrome App and it worked.
![mqttbox local](https://user-images.githubusercontent.com/16330806/41772136-0d558618-7635-11e8-8a57-20d1c6711661.png)

I tried again with following configuration 
NgxMqttClientModule.withOptions({
host: '192.186.3.39',
protocol: 'mqtt',
port: 1883,
path: '/mqtt'
})

I am not getting the console error . But i am unable to connect also.
The following is happening after I click on subscribe twice.Nothing happens when I click on send also.

![mqtt error](https://user-images.githubusercontent.com/16330806/41771894-47ce1e78-7634-11e8-8d62-fbf8ca7cb7ef.png)

Also is there a  timeout for the client ? If yes what is the duration ?

**Comment by wermerb** [comment]
I don't know what kind of broker are you using, but for example if you are using Mosquito you have to compile it to support mqtt over websocket. Probably this is why you received this error message: `WebSocket connection to 'ws://192.186.3.39:1883/mqtt' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT`.

This guide helps you compile your own Mosquito which will support mqtt over websocket: [Websockets and Mosquitto](http://www.steves-internet-guide.com/mqtt-websockets/)

Also this library is a wrapper for mqtt.js so here you can find the default settings: [MQTT.js](https://github.com/mqttjs/MQTT.js/#mqttclientstreambuilder-options)

**Comment by gopinadh39** [comment]
@wermerb 
  Its working fine thanks.

**Comment by wermerb** [comment]
@gopinadh39 
Glad i could help
